unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

set-option -g allow-rename off

set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

setw -g clock-mode-colour green

setw -g mode-style 'fg=black bg=green bold'

set -g pane-border-style 'fg=green'
set -g pane-active-border-style 'fg=yellow'

set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=green'

set -g status-left ''
set -g status-left-length 10


